"""`ckan dev`: a local CKAN with two commands and a PostgreSQL server.

    ckan dev sql | sudo -u postgres psql   # once: roles, databases, grants
    ckan dev sql test-core.ini | sudo -u postgres psql   # once: test databases
    ckan dev                               # http://localhost:5000

`ckan dev` writes `ckan.ini` in the current directory when there is none
(the output of `ckan generate config` plus a few development settings),
creates or upgrades the tables, creates the first sysadmin and starts the
development server. Every step is idempotent, so it is also the command
to run after a `git pull`.

`ckan dev sql` only prints SQL. It never connects as a superuser itself:
the person pipes it into `psql` with whatever privileges they have.
"""
from __future__ import annotations

import os
import secrets
import shutil
import sys
from typing import Any, Optional

import click
import psycopg2
from sqlalchemy.engine import make_url

from ckan.cli import load_config
from ckan.cli.generate import make_config
from ckan.lib.config_tool import config_edit_using_option_strings
from ckanext.datastore.cli import permissions_sql
from ckanext.datastore.backend.postgres import identifier, literal_string


DEFAULT_INI = "ckan.ini"
DEV_PLUGINS = (
    "activity datastore datatables_view tabledesigner image_view "
    "text_view webpage_view video_view audio_view stats"
)
SYSADMIN = "admin"

CONNECT_HINT = """\
Cannot connect to PostgreSQL with the settings in {ini}:

    {error}
Create the roles and databases once, as a PostgreSQL superuser:

    ckan dev sql | sudo -u postgres psql

or point `sqlalchemy.url` in {ini} to an existing database.
"""


def _urls(ini: Optional[str]) -> dict[str, Any]:
    """The database URLs `ckan dev` will use: from the ini when there is
    one, else the defaults `ckan generate config` writes."""
    if ini and os.path.exists(ini):
        conf = load_config(ini)

        def url(key: str) -> Any:
            value = conf.get(key)
            return make_url(str(value)) if value else None

        return {
            "main": url("sqlalchemy.url"),
            "write": url("ckan.datastore.write_url"),
            "read": url("ckan.datastore.read_url"),
        }
    return {
        "main": make_url("postgresql://ckan_default:pass@localhost/ckan_default"),
        "write": make_url(
            "postgresql://ckan_default:pass@localhost/datastore_default"),
        "read": make_url(
            "postgresql://datastore_default:pass@localhost/datastore_default"),
    }


def _role_sql(url: Any) -> str:
    return (
        "  IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = {name}) THEN\n"
        "    CREATE ROLE {ident} LOGIN PASSWORD {password} "
        "NOSUPERUSER NOCREATEDB NOCREATEROLE;\n"
        "  END IF;\n"
    ).format(
        name=literal_string(url.username),
        ident=identifier(url.username),
        password=literal_string(url.password or ""),
    )


def _database_sql(url: Any) -> str:
    # CREATE DATABASE has no IF NOT EXISTS and cannot run inside DO: use
    # psql's \gexec on a SELECT that yields the statement or nothing.
    return (
        "SELECT 'CREATE DATABASE {ident} OWNER {owner} ENCODING ''UTF8'''\n"
        "  WHERE NOT EXISTS (SELECT 1 FROM pg_database "
        "WHERE datname = {name}) \\gexec\n"
    ).format(
        ident=identifier(url.database),
        owner=identifier(url.username),
        name=literal_string(url.database),
    )


def dev_sql(ini: Optional[str]) -> str:
    """Idempotent SQL for the roles, databases and datastore grants."""
    urls = _urls(ini)
    main, write, read = urls["main"], urls["write"], urls["read"]
    roles = {u.username: u for u in (main, write, read) if u and u.username}
    out = [
        "-- Generated by `ckan dev sql`. Run as a PostgreSQL superuser, e.g.\n"
        "--   ckan dev sql | sudo -u postgres psql\n"
        "DO $$ BEGIN\n"
        + "".join(_role_sql(u) for u in roles.values())
        + "END $$;\n",
        _database_sql(main),
    ]
    if write and read and write.database:
        out.append(_database_sql(write))
        out.append(permissions_sql(
            maindb=main.database,
            datastoredb=write.database,
            mainuser=main.username,
            writeuser=write.username,
            readuser=read.username,
        ))
    return "\n".join(out)


def _write_dev_ini(ctx: click.Context, ini: str) -> None:
    ctx.invoke(make_config, output_path=ini, include_plugin=DEV_PLUGINS.split())
    config_edit_using_option_strings(ini, [
        "ckan.plugins = " + DEV_PLUGINS,
        "ckan.storage_path = %(here)s/storage",
    ], section="app:main", edit=True)
    config_edit_using_option_strings(
        ini, ["debug = true"], section="DEFAULT", edit=True)


def _check_connection(ini: str) -> None:
    url = _urls(ini)["main"]
    try:
        psycopg2.connect(str(url.render_as_string(hide_password=False))).close()
    except psycopg2.OperationalError as e:
        click.secho(CONNECT_HINT.format(ini=ini, error=e), fg="red", err=True)
        raise click.exceptions.Exit(1)


def _ensure_sysadmin(ctx: click.Context) -> None:
    from ckan import model
    from ckan.cli.sysadmin import add as sysadmin_add

    if model.Session.query(model.User).filter_by(
            sysadmin=True, state="active").first():
        return
    password = secrets.token_urlsafe(12)
    ctx.invoke(
        sysadmin_add, username=SYSADMIN, create=True,
        args=[f"email={SYSADMIN}@localhost", f"password={password}"],
    )
    click.secho(
        f"\nFirst sysadmin created: user {SYSADMIN}, password {password}\n"
        "(printed only this once)\n"
        f"  new password:  ckan user setpass {SYSADMIN}\n"
        f"  API token:     ckan user token add {SYSADMIN} dev\n",
        fg="green", bold=True)


@click.group(invoke_without_command=True)
@click.option("-H", "--host", help="Host name (default 127.0.0.1)")
@click.option("-p", "--port", help="Port number (default 5000)")
@click.option("-r", "--disable-reloader", is_flag=True,
              help="Do not restart on code changes")
@click.pass_context
def dev(ctx: click.Context, host: Optional[str], port: Optional[str],
        disable_reloader: bool):
    """Set up (if needed) and run a local CKAN. See `ckan dev sql`."""
    if ctx.invoked_subcommand:
        return
    ini = os.environ.get("CKAN_INI", DEFAULT_INI)
    if not os.path.exists(ini):
        _write_dev_ini(ctx, ini)
        click.secho(f"Wrote {ini} with development defaults", fg="green")
    _check_connection(ini)

    from ckan.cli.cli import _add_ctx_object
    from ckan.cli.db import upgrade as db_upgrade
    _add_ctx_object(ctx, ini)
    ctx.invoke(db_upgrade, version="head", plugin=None,
               skip_core=False, skip_plugins=False, load_plugin=False)
    _ensure_sysadmin(ctx)

    args = ["-c", ini, "run"]
    if host:
        args += ["--host", host]
    if port:
        args += ["--port", port]
    if disable_reloader:
        args.append("--disable-reloader")
    exe = shutil.which("ckan") or sys.argv[0]
    click.secho("ckan " + " ".join(args), fg="green")
    os.execv(exe, ["ckan"] + args)


@dev.command("sql")
@click.argument("ini", required=False, type=click.Path(exists=True))
def sql(ini: Optional[str]):
    """Print the SQL that creates the roles, databases and datastore grants
    for the settings in INI (default: ckan.ini in the current directory,
    else the development defaults). Pipe it to psql as a superuser:

        ckan dev sql | sudo -u postgres psql

        ckan dev sql test-core.ini | sudo -u postgres psql   # test databases
    """
    if ini is None:
        ini = os.environ.get("CKAN_INI", DEFAULT_INI)
        if not os.path.exists(ini):
            ini = None
    click.echo(dev_sql(ini))
